-- ============================================================
-- Seed data - Juan Paolo Dente
-- Matches the modules already in the frontend prototypes.
-- Run this AFTER schema.sql.
-- ============================================================

USE se_aware;

INSERT INTO modules (module_title, description, module_type, category, slug) VALUES
  ('Phishing', 'Fraudulent messages built to look like they came from someone you trust.', 'Free', 'phishing', 'phishing'),
  ('Spear Phishing', 'A phishing attempt tailored specifically to you or your role.', 'Free', 'spear-phishing', 'spear-phishing'),
  ('Smishing', 'Scam text messages about deliveries, banks, or accounts.', 'Free', 'smishing', 'smishing'),
  ('Vishing', 'Scam phone calls asking for one-time codes or remote access.', 'Free', 'vishing', 'vishing'),
  ('Pretexting', 'A fabricated scenario used to get access or information.', 'Free', 'pretexting', 'pretexting'),
  ('Safe Practices for Remote Workers', 'Everyday habits that close most social engineering gaps.', 'Free', 'safe-practices', 'safe-practices'),
  ('Client Impersonation', 'Someone posing as your real client mid-project.', 'Premium', 'role-based', 'client-impersonation'),
  ('Invoice and Payment Scams', 'Spoofed payment confirmations and redirected invoices.', 'Premium', 'role-based', 'invoice-scams'),
  ('Fake Job and Recruiter Offers', 'Recruitment scams targeting freelancers and VAs.', 'Premium', 'role-based', 'fake-recruiters'),
  ('Secure Client Data Handling', 'Protecting client data, passwords, and files from exposure.', 'Premium', 'role-based', 'client-data');

-- One quiz per module
INSERT INTO quizzes (module_id, title, number_of_questions)
SELECT module_id, CONCAT(module_title, ' Quiz'), 0 FROM modules;

-- Phishing (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'You receive an email from service@paypal-secure-verify.com saying your account will be limited in 24 hours unless you verify your identity. What is the strongest single reason to treat this as phishing?', JSON_ARRAY('The domain is paypal-secure-verify.com, not paypal.com', 'The email arrived outside business hours', 'It contains a company logo', 'It was sent to your work address rather than your personal one'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'A message appears to come from your bank. You hover over the button and the status bar shows bpi.com.ph.account-verify.net/login. Which domain does that link actually belong to?', JSON_ARRAY('account-verify.net', 'bpi.com.ph', 'login.bpi.com.ph', 'Both bpi.com.ph and account-verify.net equally'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'You clicked a link in a suspicious email, entered your password on the page, and then realised your mistake. You have not entered any code. What should you do first?', JSON_ARRAY('Change that password from a different device, then revoke all active sessions', 'Run a full antivirus scan and wait for the results before doing anything else', 'Reply to the email asking whether it was legitimate', 'Delete the email so nobody else in your household clicks it'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'A printed flyer in a coworking space shows a QR code offering free Wi-Fi. You scan it and your phone previews the address before opening it. What is the right move?', JSON_ARRAY('Read the previewed address carefully and do not continue if it is unfamiliar', 'Continue, because a QR code printed on paper cannot be malicious', 'Continue, but close the page quickly if it looks strange', 'Turn off mobile data first, then continue'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'An email from a courier says a parcel is held and asks you to sign in to reschedule. You are genuinely expecting a delivery. What is the safest way to check?', JSON_ARRAY('Open the courier app you already have installed, or type their website yourself', 'Click the link, since you really are expecting a package', 'Forward the message to a colleague and ask what they think', 'Reply to the email and ask the courier to confirm it is genuine'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'A phishing page asked for your password and then, on the next screen, for the six-digit code your bank had just texted you. You entered both. What does entering the code most likely mean?', JSON_ARRAY('The attacker was logging in as you in real time and now has access', 'Nothing, because one-time codes expire after a few minutes', 'Nothing, because the code only works on the bank''s real website', 'The code was harvested for sale but cannot be used immediately'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'What is the defining characteristic of a phishing attack?', JSON_ARRAY('It impersonates a trusted organisation to make you surrender something valuable', 'It exploits an unpatched vulnerability in your operating system', 'It encrypts your files and demands payment', 'It floods a website with traffic until it goes offline'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'Why is poor grammar no longer a reliable way to spot phishing?', JSON_ARRAY('Translation tools and language models now produce fluent, professional text', 'Email clients silently correct grammar in incoming messages', 'Attackers are required to use templates approved by mail providers', 'Grammar was never used by anyone as a phishing signal'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'What is QR phishing, sometimes called quishing?', JSON_ARRAY('Hiding a malicious link inside a QR code so it cannot be inspected before scanning', 'Generating fake QR codes that install apps without any user action', 'Using a QR code to bypass multi-factor authentication automatically', 'Encrypting a phishing email so mail filters cannot read it'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'Which request should never come from a legitimate organisation by email?', JSON_ARRAY('Your password or a one-time PIN', 'Confirmation that you received a statement', 'A request to update your mailing address in your account settings', 'Notification of a scheduled maintenance window'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'Why do phishing messages so often impose a deadline of a few hours?', JSON_ARRAY('Time pressure reduces the chance you will stop and verify', 'Mail servers delete unread promotional messages after a day', 'Short deadlines make messages more likely to reach the inbox', 'It is a legal requirement for account security notices'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'What is the safest general habit when a message says your account needs attention?', JSON_ARRAY('Never sign in from a link you did not go looking for', 'Open the link but check for a padlock icon before signing in', 'Sign in only if the message uses your full name', 'Sign in from your phone rather than your computer'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'Which attachment types most often carry a phishing payload?', JSON_ARRAY('.html .htm .zip .iso, and documents demanding that macros be enabled', '.jpg and .png images', '.txt plain-text notes', '.mp3 audio files'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'A phishing email uses your bank''s exact logo, fonts, and footer layout. What does that prove?', JSON_ARRAY('Nothing: those assets are copied from the bank''s own public website', 'That the message passed the bank''s security checks', 'That the sender has access to the bank''s internal systems', 'That the message is at least partly genuine'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'phishing'), 'After a phishing compromise of an email account, which follow-up check is most often overlooked?', JSON_ARRAY('Looking for hidden mail forwarding rules added by the attacker', 'Clearing the browser cache', 'Reinstalling the email application', 'Changing the account''s display name'), 0, 14);

-- Spear Phishing (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'A recruiter messages you, names a real client from your portfolio, praises that specific project, and offers an above-market contract. To proceed you must take a skills assessment and sign in with your Google account on northbridge-careers.talentportal-hr.com. What is the clearest sign this is an attack?', JSON_ARRAY('A skills assessment is asking for your Google credentials on a third-party domain', 'The recruiter contacted you without an introduction', 'The rate offered is higher than you usually charge', 'The message was sent through a professional network rather than email'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'An email from your longest-standing client''s finance contact arrives on a Friday at 4:50 PM. The signature and tone are exactly right, but the address is one character different from the one in your existing thread. What should you do?', JSON_ARRAY('Call the contact on the number you already had before this email arrived', 'Reply to the new address and ask them to confirm their identity', 'Compare the writing style to previous emails and decide from that', 'Wait until Monday and see whether they follow up'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'A message references your current project, your rate, and your recent client (all accurate) and asks you to review an attached brief that requires a login to open. What do those accurate details actually prove?', JSON_ARRAY('Nothing about identity. They are all available from public profiles', 'That the sender has worked with you before', 'That the sender has legitimate access to your client''s systems', 'That the message came from inside your client''s network'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'You check the recruiter''s profile. It was created three weeks ago, has 41 connections, no posts, and the company page it links to has no other employees. How should you read this?', JSON_ARRAY('A strong signal of a fabricated identity: verify the company independently', 'Normal for a recruiter who has just switched employers', 'Irrelevant, since profile age is not related to legitimacy', 'Proof of fraud on its own, so no further checking is needed'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'A message claiming to be from your supervisor asks you to buy gift cards for a client giveaway and send the codes, adding: ''I am in back-to-back meetings, email only please, and keep this between us until the announcement.'' Which element most reliably identifies this as an attack?', JSON_ARRAY('Untraceable payment combined with confidentiality and a blocked verification channel', 'The fact that a supervisor emailed rather than called', 'That the request came during working hours', 'That gift cards were mentioned by brand name'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'You are a virtual assistant. A person introduces themselves as a new project manager at a client company, chats pleasantly for three days about deliverables, then asks for the shared login to the client''s social media accounts. What is the correct response?', JSON_ARRAY('Verify with your existing contact at the client before sharing anything', 'Share the credentials, since the relationship is now established', 'Share a limited-permission account instead, without verifying', 'Ask them to prove identity by sending a photo of their company ID'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'What distinguishes spear phishing from ordinary phishing?', JSON_ARRAY('It is written for one specific target using researched personal details', 'It is sent by SMS instead of email', 'It always contains a malicious attachment', 'It targets only large corporations, never individuals'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Which source do attackers most commonly use to research a freelance target?', JSON_ARRAY('Public professional profiles, portfolio sites, and social media posts', 'Encrypted messaging apps', 'The target''s internet service provider records', 'Government tax databases'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'What is a homoglyph domain?', JSON_ARRAY('A domain using visually similar characters, such as a capital I in place of a lowercase l', 'A domain registered in more than one country at once', 'A domain that redirects to a different site after a delay', 'A domain with an unusually long name'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Why is verifying through a channel that predates the message so important?', JSON_ARRAY('Any contact detail supplied in the message itself may belong to the attacker', 'Older channels are technically more secure than newer ones', 'It creates a legal record of the verification', 'It is faster than replying directly'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Which request pattern is a reliable red flag in a job or client approach?', JSON_ARRAY('Signing in with your email account to access an assessment or portal', 'A request for your portfolio or work samples', 'A request for your availability and rate', 'A request for a video call before contracting'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Why do these messages so often arrive late on a Friday or just before a holiday?', JSON_ARRAY('The people who could verify the request are least reachable then', 'Spam filters are switched off outside business hours', 'Recipients read email more carefully at those times', 'It is when most legitimate invoices are issued'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Which term describes an attack impersonating a supplier or executive to redirect payments?', JSON_ARRAY('Business email compromise', 'Denial of service', 'SQL injection', 'Credential stuffing'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'You receive a spear phishing attempt impersonating a client. Beyond protecting yourself, what should you do?', JSON_ARRAY('Warn the impersonated client so their other contractors can be alerted', 'Nothing further, since you did not fall for it', 'Publicly post the message so others can see it', 'Reply to the attacker to confirm you are not interested'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'spear-phishing'), 'Why is a display name an unreliable indicator of a sender''s identity?', JSON_ARRAY('It is free text that anyone can set to any value', 'It is generated automatically by the mail server', 'It is only visible on mobile devices', 'It changes every time a message is forwarded'), 0, 14);

-- Smishing (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'You receive: ''LBC EXPRESS: Your parcel LB4471982PH is on hold due to an incomplete address. Pay the ₱48 redelivery fee within 12 hours or the item will be returned.'' with a link to lbc-redelivery.info. Why is the fee kept so small?', JSON_ARRAY('A trivial amount discourages scrutiny, and the real target is your card details', 'Small transactions cannot be reversed by banks', 'It is the maximum a scam can charge without triggering alerts', 'It covers the attacker''s cost of sending the messages'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'A text appears in the same conversation thread as genuine messages from your bank, using the same sender ID. What does that prove about its origin?', JSON_ARRAY('Nothing: alphanumeric sender IDs can be spoofed and phones thread by ID', 'That it genuinely came from your bank''s messaging system', 'That your phone has verified the sender cryptographically', 'That your bank''s systems have been breached'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'A text says you have won ₱50,000 in a raffle run by a mall you have shopped at. To claim it you must send a processing fee via e-wallet. Which element identifies this as a scam most reliably?', JSON_ARRAY('Being asked to pay a fee to receive a prize', 'That the mall is one you have actually visited', 'That the amount is a round number', 'That the message arrived by SMS rather than email'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'A text claims a ₱12,000 transfer from your account was blocked and gives a hotline number to call immediately. What is the safest response?', JSON_ARRAY('Call the number printed on your card or in the bank''s official app instead', 'Call the number in the message, since blocked transfers are time-sensitive', 'Reply STOP to the message to halt the transaction', 'Forward the message to your bank and wait for their reply'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'A friend texts: ''Hey, I accidentally sent my verification code to your number. Can you forward it to me?'' What is happening?', JSON_ARRAY('Someone is trying to take over an account and needs the code you received', 'A genuine mis-typed phone number, so forwarding it is harmless', 'A network fault that duplicated the message', 'A test message from the mobile provider'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'You tapped a link in a scam text, the page loaded, and you closed it immediately without typing anything. What is the appropriate level of concern?', JSON_ARRAY('Low: you almost certainly are not compromised, but do not revisit the link', 'Severe: simply loading the page installs malware on modern phones', 'None at all: no follow-up is ever needed after visiting a page', 'High. You must factory reset your phone immediately'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'What is smishing?', JSON_ARRAY('Phishing delivered through SMS text messages', 'Phishing conducted over a voice call', 'Malware that spreads through Bluetooth', 'Intercepting messages on a public Wi-Fi network'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'Why is it harder to evaluate a text than an email?', JSON_ARRAY('There is no full sender address, no signature, and links are usually shortened', 'Text messages cannot be screenshotted for review', 'Phones display texts for a limited time only', 'SMS cannot contain links at all'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'Which three lures account for the majority of scam texts?', JSON_ARRAY('Package delivery fees, prize or raffle wins, and urgent bank alerts', 'Weather warnings, election notices, and traffic updates', 'Software updates, storage warnings, and app reviews', 'Utility bills, school notices, and appointment reminders'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'Why should you avoid replying to a scam text, even to say no?', JSON_ARRAY('A reply confirms your number is active, making it more valuable to resell', 'Replying automatically subscribes you to a paid service', 'Your reply gives the sender access to your contacts', 'Replying is a criminal offence in most jurisdictions'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'You entered card details on a smishing page. What is the first action?', JSON_ARRAY('Call your bank''s official hotline immediately and have the card blocked', 'Wait to see whether any charge actually appears', 'Change your online banking password and take no further action', 'Report the message to your network provider first'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'Why do attackers use link shorteners in text messages?', JSON_ARRAY('They hide the destination completely until it is opened', 'They make pages load noticeably faster', 'They are required for links to work in SMS', 'They prevent the message from being reported'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'What is the single most reliable habit against smishing?', JSON_ARRAY('Never act inside the message: verify through the app or site you already use', 'Only open links from senders in your contacts list', 'Read texts on a computer rather than a phone', 'Disable SMS previews on your lock screen'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'How should this be read?', JSON_ARRAY('A common job scam that typically leads to advance fees or money laundering', 'A normal modern recruitment process for remote roles', 'A legitimate approach if the company has a website', 'Safe as long as you never share your bank details'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'smishing'), 'Why is SMS the weakest form of multi-factor authentication?', JSON_ARRAY('It is vulnerable to SIM-swap fraud and to social engineering by phone', 'Text messages are never delivered reliably', 'Codes sent by SMS do not expire', 'SMS codes are always shorter than app-generated ones'), 0, 14);

-- Vishing (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'A caller says: ''This is the fraud team. We have held a ₱48,750 transfer, but the hold expires in fifteen minutes. I am sending a six-digit code to your phone. Please read it back so I can confirm your identity.'' What is actually happening?', JSON_ARRAY('The attacker is signing in as you and needs the code to complete it', 'The bank is performing a standard identity verification', 'The code confirms the transfer has been cancelled', 'The call is genuine but the agent is following the wrong procedure'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Your phone shows your bank''s real hotline number as the incoming caller ID. What does that tell you about the call''s origin?', JSON_ARRAY('Nothing: caller ID is display text and is trivially spoofed', 'That the call definitely came from the bank''s system', 'That the call was routed through a verified carrier', 'That the number has been checked against a fraud database'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Someone claiming to be IT support says your account is compromised and asks you to install AnyDesk so they can secure your machine. What should you do?', JSON_ARRAY('Refuse, hang up, and contact IT through a channel you already had', 'Install it but watch the screen and disconnect if anything looks wrong', 'Install it only if they can name your manager', 'Ask them to email the request first, then install it'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'A caller states your full name and the last four digits of your card, then asks you to confirm your online banking password. How should you interpret the accurate details?', JSON_ARRAY('They are cheap to obtain from breaches and are offered to buy your trust', 'They prove the caller has access to your bank account records', 'They confirm the call is internal to the bank', 'They indicate the bank''s database has been breached'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'You receive a voice note that sounds exactly like your client''s voice, urgently asking you to transfer funds to a new account today. What is the appropriate response?', JSON_ARRAY('Verify by calling them on the number you already had, on a separate channel', 'Act on it, since you clearly recognise the voice', 'Reply to the voice note asking them to confirm', 'Transfer a smaller test amount first to check'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'You realise mid-call that it is a scam. The caller becomes insistent that you must not hang up or the hold will fail. What should you do?', JSON_ARRAY('Hang up immediately: ending a call is always safe', 'Stay on the line and try to gather information about the caller', 'Put the phone down without hanging up so they think you are still there', 'Tell them you know it is a scam and warn them off'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'What is vishing?', JSON_ARRAY('Social engineering conducted by voice call or voice message', 'Phishing sent through video conferencing links', 'Malware that records audio from a device', 'Intercepting calls on a shared network'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Why is a phone call often more effective than an email for an attacker?', JSON_ARRAY('It demands an immediate answer and makes scepticism socially awkward', 'Calls cannot be recorded as evidence', 'Phone networks have no fraud detection at all', 'People trust unknown numbers more than unknown addresses'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Which rule defeats nearly every vishing call?', JSON_ARRAY('Never read out, type, or forward a one-time code to anyone', 'Only answer calls from numbers in your contacts', 'Always ask the caller for an employee number', 'Record every call you receive'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Why should you use a different phone to call back after a suspicious call?', JSON_ARRAY('Some scams hold the line open so a callback reaches the same attacker', 'Your original phone may have been infected during the call', 'Callbacks from the same number are automatically blocked', 'Different phones use different, more secure networks'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'A caller asks you to move funds to a ''safe holding account'' during an investigation. What is this?', JSON_ARRAY('Always fraud: no such account exists in legitimate banking', 'A standard fraud-prevention procedure at most banks', 'Legitimate only if the account is in your own name', 'Legitimate only when arranged by the fraud department'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'You installed remote-access software during a scam call. What is the first step?', JSON_ARRAY('Disconnect the device from the internet, then uninstall it', 'Run antivirus while remaining connected', 'Change all your passwords on the same device immediately', 'Restart the device and continue using it normally'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Why do attackers ask for payment in gift cards, e-wallets, or cryptocurrency?', JSON_ARRAY('Those transfers are effectively irreversible', 'They are the only methods that work internationally', 'They avoid all transaction fees', 'They are the fastest way to move small amounts'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'What simple measure helps most against AI voice cloning?', JSON_ARRAY('Agreeing a code word with family and key clients that has never been posted online', 'Only accepting calls from saved contacts', 'Speaking in a regional language during calls', 'Recording all calls for later comparison'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'vishing'), 'Money left your account through a vishing call an hour ago. What matters most now?', JSON_ARRAY('Calling the bank''s official hotline immediately to attempt a recall', 'Filing a police report before contacting the bank', 'Emailing the bank so there is a written record', 'Waiting for the transaction to clear before reporting'), 0, 14);

-- Pretexting (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'An email from your client''s finance contact says they have moved to a new banking partner and asks you to update the account on your March invoice. The old account ''closes on the 28th''. The domain is cortez-Iogistics.com. What is the decisive red flag?', JSON_ARRAY('A capital I replaces the lowercase l in the domain. It is a lookalike', 'The message mentions a specific date', 'Finance contacted you rather than your project manager', 'The email included an account number in plain text'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'A supplier you have worked with for two years emails to say their bank details have changed. The address matches your existing thread exactly and the tone is normal. What should you do before paying?', JSON_ARRAY('Call them on the number you already had and confirm the account number aloud', 'Pay, since the email address matches your existing thread', 'Reply asking them to confirm the change in writing', 'Send a small test payment first and wait for acknowledgement'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'A new contact introduces themselves as a project manager at your client, asks a harmless question about a deliverable, chats for several days, and only then asks for access to a shared account. What does the friendly build-up represent?', JSON_ARRAY('The pretext itself: the harmless contact exists to make the later request unremarkable', 'Evidence of a genuine working relationship', 'A normal onboarding process for new staff', 'An unrelated coincidence before the real attack'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'The sender declines a phone call, explaining they are ''in workshops all day, email reaches me fine'', and asks you to keep the payment change between the two of you. How should those two details be read together?', JSON_ARRAY('As deliberate blocking of verification, a core pretexting technique', 'As a reasonable explanation from a busy colleague', 'As evidence the request is confidential but genuine', 'As irrelevant to the legitimacy of the request'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'You already paid an invoice to the new account and then discovered the domain was a lookalike. What is the first action?', JSON_ARRAY('Call your bank immediately and request a recall, then tell the real client', 'Email the attacker demanding the money back', 'Wait to see whether the payment bounces', 'File a police report before contacting anyone else'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Someone claiming to be from a client''s IT department asks you to confirm which project management tools you use and who approves your invoices. They ask for nothing sensitive. How should you treat this?', JSON_ARRAY('As reconnaissance for a later attack: verify before answering', 'As harmless, since no credentials were requested', 'As a routine audit that requires cooperation', 'As a survey that can be safely ignored without any follow-up'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'What is pretexting?', JSON_ARRAY('Building a believable cover story that makes a later request seem ordinary', 'Sending bulk emails with a malicious attachment', 'Guessing passwords using leaked credential lists', 'Intercepting traffic on an unsecured network'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'How does pretexting differ from ordinary phishing?', JSON_ARRAY('It invests time building a relationship before making any request', 'It is always delivered by SMS', 'It relies on a software vulnerability', 'It targets only personal, never professional, accounts'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Which single rule prevents most invoice fraud?', JSON_ARRAY('Confirm every change of payment details by voice, on a number you already had', 'Only accept invoices as PDF attachments', 'Require all invoices to be signed', 'Pay invoices only on fixed days of the month'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Why are remote workers particularly exposed to pretexting?', JSON_ARRAY('They routinely work with people they have never met, so a plausible stranger is normal', 'They use less secure devices than office workers', 'They are legally responsible for client payments', 'Their email providers offer weaker filtering'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Why is replying inside the original email thread a useful check?', JSON_ARRAY('If the sender address was spoofed, your reply reaches the real person instead', 'Threaded replies are encrypted by default', 'It prevents the attacker from reading your message', 'It automatically verifies the sender''s domain'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Which timing pattern is typical of a pretexting request?', JSON_ARRAY('Just before a finance cut-off, a holiday, or while the real person is away', 'Early on Monday morning', 'During scheduled system maintenance', 'Immediately after a public holiday ends'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'A request is unusually small and harmless, and the next one is not. What does that pattern indicate?', JSON_ARRAY('Escalation, a hallmark of a pretext being established', 'A genuine relationship developing naturally', 'An automated system sending messages out of order', 'A sign the sender is inexperienced'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'Why does a two-minute verification call cost an attacker so much?', JSON_ARRAY('It breaks the pretext by introducing a channel they do not control', 'It creates a legal record that can be used in court', 'It alerts the telephone network to the fraud', 'It gives the bank time to freeze the transfer automatically'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'pretexting'), 'What is the safest response to a request for an organisation chart, client list, or copy of an invoice?', JSON_ARRAY('Verify who is asking and why before sending anything', 'Send it, since none of it is technically confidential', 'Send a redacted version without verifying', 'Ignore it entirely and take no further action'), 0, 14);

-- Client Impersonation (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'A person introduces themselves as your client''s new project manager on Monday, asks a harmless question about a deliverable on Wednesday, then on Friday asks for the analytics portal login because ''IT are slow with provisioning''. What is the Wednesday message doing?', JSON_ARRAY('Making Friday''s request feel like a continuation rather than a first approach', 'Genuinely checking a figure before a board deck', 'Testing whether your email address still works', 'Nothing, it is unrelated to the attack'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'The same message adds that they would ''rather not hold up your invoice approval while we wait''. What is that clause doing?', JSON_ARRAY('Attaching something you want to compliance, so hesitating feels costly', 'Being helpful about your payment timeline', 'Explaining an unrelated finance process', 'Establishing that they have authority over payments'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'You want to confirm whether this new project manager is genuine. Who should you ask?', JSON_ARRAY('Your existing contact at the client, through the channel you already had', 'The new project manager, by replying and asking them to confirm', 'The client''s public support email address', 'Nobody, since the details they gave were accurate'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'You check and the email address is genuinely your client''s real address, with the real thread history beneath it. What does that most likely mean?', JSON_ARRAY('Their mailbox has been compromised, which is the hardest version to spot', 'The request must be legitimate', 'The attacker has spoofed the display name only', 'Your own account has been compromised'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'A client contact you have never spoken to asks you to move a conversation to a personal WhatsApp number because ''company chat is being migrated''. How should you read this?', JSON_ARRAY('As an attempt to move you somewhere unmonitored and unverifiable', 'As a normal consequence of an IT migration', 'As a convenience, since chat apps are faster', 'As harmless, provided you do not share credentials there'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'You already added the impersonator to a shared Drive folder yesterday. What is the first thing to do?', JSON_ARRAY('Revoke the access in the platform''s sharing settings, then tell the real client', 'Delete the folder entirely so nothing can be reached', 'Email the impersonator and withdraw the invitation', 'Wait to see whether anything is actually downloaded'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'Why are freelancers more exposed to client impersonation than office employees?', JSON_ARRAY('An unfamiliar contact is normal in client work, so instincts do not fire', 'Freelancers use weaker devices than employees', 'Client data is inherently more valuable', 'Freelancers are legally responsible for client security'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'In this attack, what does the attacker usually want first?', JSON_ARRAY('Access, because it is quieter and rarely questioned', 'A single large payment', 'Your personal identity documents', 'Control of your own website'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'Why do attackers impersonate a middle-ranking contact rather than the CEO?', JSON_ARRAY('Senior enough to give instructions, junior enough that you would not know them', 'Executives are better protected technically', 'Middle managers have more system access', 'It is easier to find their photographs'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'How does a genuine staff handover normally reach you?', JSON_ARRAY('The person leaving introduces the person arriving', 'The new person introduces themselves directly', 'Through an automated notification from the client''s HR system', 'It is usually not announced at all'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'Why is delegated access safer than a shared login?', JSON_ARRAY('It can be revoked cleanly and leaves an audit trail that protects you too', 'It is encrypted where shared passwords are not', 'It gives you more permissions', 'It removes the need for multi-factor authentication'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'A request explains that the normal process is the obstacle: IT are slow, procurement is backed up, the portal is down. What is that?', JSON_ARRAY('A standard technique for routing around the controls that would catch them', 'An honest description of a common problem', 'A sign the request came from inside the organisation', 'Irrelevant to whether the request is genuine'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'What should you agree with a client at the start of a contract to prevent this?', JSON_ARRAY('Who is authorised to request access or payment changes, and that new people are introduced by them', 'That all communication happens by email only', 'That you will hold a copy of their customer database', 'That you will not work with their competitors'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'You verified and the contact was fake. Nothing was shared. What should you still do?', JSON_ARRAY('Tell the real client the same day so their other contractors can be warned', 'Nothing, since no harm was done', 'Post the details publicly as a warning', 'Reply to the attacker to tell them you know'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-impersonation'), 'Why does a request to keep something confidential belong on a red-flag list?', JSON_ARRAY('Secrecy removes the cross-check that would expose the impersonation', 'Confidentiality is never legitimate in client work', 'It indicates the sender is junior', 'It means the message was sent to many people at once'), 0, 14);

-- Invoice and Payment Scams (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'A client says their accounts assistant overpaid you, ₱62,000 instead of ₱31,000. The money really has landed. They ask you to return the difference to a supplied account. What is happening?', JSON_ARRAY('The incoming payment will be reversed later, and the refund you send is your own money', 'A genuine administrative error you should help correct', 'A test transaction before a larger contract', 'A tax arrangement that requires a returned portion'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'The same email claims their finance system will not let them reverse a completed transfer. How should you treat that claim?', JSON_ARRAY('As false, because a real bank can always reverse its own outbound payment', 'As a plausible limitation of small business banking', 'As a reason to act faster on their behalf', 'As irrelevant to the decision'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'A supplier you have paid monthly for two years emails to say their bank details have changed. The email address matches your existing thread exactly. What should you do before paying?', JSON_ARRAY('Call them on a number you already had and confirm the account number aloud', 'Pay, since the address matches your thread', 'Reply asking for written confirmation on letterhead', 'Send a small test payment and wait for acknowledgement'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'The bank-change email arrives on a Thursday and says the old account closes on the 28th, with anything sent there bouncing back and delaying you a cycle. What is the deadline for?', JSON_ARRAY('Compressing the time available to verify, and adding a penalty for pausing', 'Reflecting a genuine banking migration timetable', 'Meeting a regulatory requirement for account changes', 'Nothing, deadlines are normal in finance'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'You paid the new account on Monday. On Thursday the real supplier chases the invoice. What is the first call you make?', JSON_ARRAY('Your bank, asking for a recall and a fraud reference number', 'The supplier, to apologise and arrange a repayment plan', 'The police, to file a report before anything else', 'The email provider, to report the spoofed address'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'A new client offers to pay a subcontractor through you: they will send you the funds and you forward them on, keeping your fee. How should you respond?', JSON_ARRAY('Refuse. Money passing through your account for someone else is a laundering pattern', 'Accept, since the fee is genuine work', 'Accept but only for amounts under a set threshold', 'Accept if they provide the subcontractor''s contract'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Why are freelancers exposed to invoice fraud from two directions?', JSON_ARRAY('They both send invoices and pay suppliers or subcontractors', 'They use personal bank accounts for business', 'They work across multiple time zones', 'They rarely use written contracts'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Why is a payment instruction rarely questioned?', JSON_ARRAY('Bank changes really do happen, and querying one feels like an accusation', 'Payment emails bypass spam filters', 'Finance systems verify account details automatically', 'Most people cannot read account numbers accurately'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'The attacker usually waits for a real invoice before striking. Why?', JSON_ARRAY('A payment that was already expected raises no questions', 'Invoices contain the account number they need', 'It gives them time to register a domain', 'Banks scrutinise unexpected payments more closely'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Which single rule prevents most invoice fraud?', JSON_ARRAY('Confirm every change of payment details by voice, on a number you already had', 'Only accept invoices as password-protected PDFs', 'Pay all invoices on a fixed day of the month', 'Require a signature on every invoice'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Why does replying inside the original email thread help?', JSON_ARRAY('If the address was spoofed, the reply reaches the real person instead', 'Threaded replies are encrypted end to end', 'It prevents the attacker from reading the message', 'It automatically verifies the sender domain'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'What should you put on your own invoices to protect your clients and your payments?', JSON_ARRAY('A line stating your bank details never change and any email claiming otherwise should be verified by phone', 'A watermark showing the invoice is original', 'Your full bank statement for the period', 'A clause waiving liability for misdirected payments'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Why do attackers ask for gift cards, e-wallet transfers, or cryptocurrency?', JSON_ARRAY('Those transfers are effectively irreversible', 'They avoid transaction fees', 'They are the only methods that work internationally', 'They are faster to process than bank transfers'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'Why should you periodically check your sent folder and mail rules?', JSON_ARRAY('A silent forwarding rule is how an attacker reads your invoices', 'It frees up mailbox storage', 'Mail providers require it for compliance', 'It improves email deliverability'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'invoice-scams'), 'How long can an overpayment take to be reversed by the sending bank?', JSON_ARRAY('Days or even weeks, long after you have sent the refund', 'Within one hour, so the risk window is short', 'It cannot be reversed once it has cleared', 'Exactly 24 hours in all cases'), 0, 14);

-- Fake Job and Recruiter Offers (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'A role offers ₱45,000 a month for 8 to 10 hours a week. Client funds are transferred into your personal account, you deduct a 7% commission, and forward the balance to supplier accounts they provide. What is this role?', JSON_ARRAY('Money laundering, regardless of how it is described', 'A legitimate payment processing role', 'An advance fee scam', 'A credential harvesting attempt'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'The same advert says the company is ''setting up local corporate banking and this bridges the gap for the next quarter''. How should you read that explanation?', JSON_ARRAY('As a cover story, since no real business bridges banking through staff accounts', 'As a plausible situation for a company entering a new market', 'As a reason the role is temporary but genuine', 'As a detail that needs verifying with their finance team'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'The offer comes from careers@northbridge-digital.recruit-hub.co. Who owns that address?', JSON_ARRAY('recruit-hub.co, since the real domain is the part before the first single slash', 'northbridge-digital.com', 'Both companies jointly', 'It cannot be determined from the address'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'A recruiter names your actual portfolio project, praises it specifically, and offers to skip the first screening round because of your background. What is the skipped step doing?', JSON_ARRAY('Removing the conversation where the approach would fall apart', 'Genuinely reflecting your seniority', 'Speeding up a competitive hiring process', 'Reducing the company''s recruitment costs'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'To proceed, you must complete a skills assessment on their portal and sign in with your Google account so the results attach to your profile. What is the assessment for?', JSON_ARRAY('Nothing. The sign-in page is the entire attack', 'Filtering candidates before interview', 'Verifying your identity for payroll', 'Testing whether you can follow instructions'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'Two payments have already passed through your account for a ''payment operations'' role before you realised what it was. What should you do?', JSON_ARRAY('Stop immediately and contact your bank yourself to explain what happened', 'Return the money to the sender and cut contact quietly', 'Wait to see whether the bank notices', 'Close the account and open a new one elsewhere'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'Why do job scams land hardest on freelancers between contracts?', JSON_ARRAY('Wanting the outcome to be real lowers scrutiny, and that state is predictable', 'Freelancers have weaker email security', 'Recruiters rarely contact employed people', 'Contract gaps are visible on public profiles'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'What does a legitimate hiring process never do?', JSON_ARRAY('Charge you for training, equipment, certification, or a background check', 'Ask for a portfolio or work samples', 'Request a video interview', 'Ask about your availability and rate'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'When does a real employer collect government ID and bank details?', JSON_ARRAY('After a signed contract, through an HR system', 'In the first message, to confirm you are a real person', 'Before the interview, to speed up onboarding', 'Never, under any circumstances'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'Why do these approaches move to Telegram or WhatsApp early?', JSON_ARRAY('Those channels are unmonitored, unreportable, and leave no platform record', 'They are more secure for sharing documents', 'Recruiters prefer instant messaging', 'It avoids email spam filters'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'What is the fastest useful check before replying to an unsolicited offer?', JSON_ARRAY('Search the company name plus the word scam, and check their real careers page', 'Ask the recruiter for a photo of their company ID', 'Check whether the email has a professional signature', 'Look at how many connections the recruiter has'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'Why is the money mule variant more damaging than losing a password?', JSON_ARRAY('The transactions are in your name and intent is hard to prove afterwards', 'The amounts involved are always larger', 'Bank accounts cannot be reopened once frozen', 'It cannot be reported to the authorities'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'Which recruiter profile pattern is a strong warning sign?', JSON_ARRAY('Created recently, few connections, no posting history, company page with no other staff', 'A profile with more than 500 connections', 'A recruiter who works for an agency rather than the employer', 'A profile photograph taken professionally'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'What is the two-part rule that covers nearly every version of this attack?', JSON_ARRAY('A real job costs you nothing and never asks for your credentials', 'Never accept work from overseas companies', 'Only apply through job boards, never by referral', 'Always insist on payment before starting work'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'fake-recruiters'), 'You sent ID documents before realising the role was fake. What is a sensible follow-up?', JSON_ARRAY('Record what was sent and when, and watch for accounts opened in your name', 'Nothing, since ID documents are public information', 'Report yourself to the credit bureau as compromised', 'Change your name on official records'), 0, 14);

-- Secure Client Data Handling (15 questions)
INSERT INTO quiz_questions (quiz_id, question_text, options, correct_option_index, order_index) VALUES
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Your real client, on her genuine account, asks you to pull the full customer export from the CRM into your own Drive because their IT have locked external sharing again. What is the best response?', JSON_ARRAY('Ask which fields she needs and offer to work inside their system instead', 'Do it, since the request is genuine and she is authorised', 'Refuse outright and explain it is against best practice', 'Do it but delete the file at the end of the week'), 0, 0),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Six months later your Drive is breached, and it still contains that customer export. Whose storage is the disclosure conversation about?', JSON_ARRAY('Yours, because the data was outside the client''s controls and retention policy', 'The client''s, since it is their customer data', 'The CRM vendor''s, since the data originated there', 'Nobody''s, because you had permission to hold it'), 0, 1),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'A client offers you the owner-level login for their advertising account so you can manage campaigns. What should you ask for instead?', JSON_ARRAY('Your own user account with the permissions the work needs', 'The owner login, but stored in a password manager', 'A shared login with the password changed monthly', 'Read-only access, then request changes by email'), 0, 2),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'You are asked to install remote-access software so a client''s ''IT contractor'' can configure your machine for their systems. How should you respond?', JSON_ARRAY('Refuse, and verify the request with your known contact at the client', 'Allow it, since the client has authorised their own contractor', 'Allow it but watch the screen throughout', 'Install it on a spare device instead'), 0, 3),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'A project closed four months ago. The client''s files are still in your Downloads folder and your cloud backup. What does that represent?', JSON_ARRAY('Pure liability: no upside for you, permanent exposure', 'Sensible record keeping in case of a dispute', 'A neutral situation, since the project is finished', 'An asset you could reuse for similar work'), 0, 4),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'You realise client data has been exposed through your machine. Your first instinct is to tidy up the folder before telling anyone. Why is that the wrong move?', JSON_ARRAY('Deleting destroys evidence and looks far worse in hindsight than the incident', 'It wastes time that should be spent on the disclosure', 'Cloud backups make deletion pointless anyway', 'It is not wrong, provided you tell the client afterwards'), 0, 5),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Why is a contractor often the softer route to a company''s data?', JSON_ARRAY('The same data sits on a machine without a security team or monitored logins', 'Contractors are less trustworthy than employees', 'Contractors keep data for longer by law', 'Company networks are rarely protected'), 0, 6),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Which habit removes the most risk?', JSON_ARRAY('Collecting less: fewer fields, shorter access, only what the task needs', 'Encrypting every file individually', 'Backing up client data to a second cloud provider', 'Renaming files so their contents are not obvious'), 0, 7),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Why should client work happen inside the client''s own systems where possible?', JSON_ARRAY('It keeps the data inside their controls, retention policy, and audit trail', 'Their systems are always more secure than yours', 'It reduces your internet usage', 'It transfers all legal liability to them'), 0, 8),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'What is the minimum acceptable separation between client work and personal use?', JSON_ARRAY('A separate browser profile, with a separate user account being better', 'A separate folder on the same desktop', 'A different web browser tab', 'No separation is needed if you live alone'), 0, 9),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Why does full-disk encryption matter for a freelancer?', JSON_ARRAY('Laptops are stolen for the hardware, and an unencrypted one hands over every client file', 'It prevents malware from running', 'It is required by the Data Privacy Act for all devices', 'It speeds up file access'), 0, 10),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'How should credentials be shared with you?', JSON_ARRAY('Through the platform''s permission system, or a password manager''s sharing feature', 'By email, in two separate messages', 'By chat, deleted immediately afterwards', 'By phone, so nothing is written down'), 0, 11),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Client data belonging to other people was exposed. Why must you tell the client immediately?', JSON_ARRAY('They may have notification obligations with clocks already running', 'They can delete the data remotely', 'It transfers responsibility to them', 'Their insurance requires it within 24 hours'), 0, 12),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'What belongs in your contract about client data?', JSON_ARRAY('How it is stored, how long you keep it, and what happens at the end', 'A clause waiving all liability for breaches', 'A right to reuse the data in your portfolio', 'Nothing, since it is covered by law already'), 0, 13),
  ((SELECT q.quiz_id FROM quizzes q JOIN modules m ON m.module_id = q.module_id WHERE m.slug = 'client-data'), 'Which sentence summarises this module?', JSON_ARRAY('Hold as little as possible, for as short a time as possible, in a place the client can see', 'Encrypt everything and keep a backup of every project', 'Never accept access to a client''s live systems', 'Store client data only on removable drives'), 0, 14);

-- Refresh each quiz's question count to match what was just inserted.
UPDATE quizzes q SET q.number_of_questions =
  (SELECT COUNT(*) FROM quiz_questions qq WHERE qq.quiz_id = q.quiz_id);

-- ============================================================
-- Create the first admin account manually after running this file:
--   1. Register a normal account through the site (or via POST /api/auth/register)
--   2. UPDATE users SET role = 'admin' WHERE email = 'your@email.com';
-- There is no self-service way to become an admin, on purpose.
-- ============================================================
